### ISSUE TITLE
RG280V - error starting Atari 2600 roms

### ISSUE THREAD

**Issue by rudi282** [eduardofilo/RG350_ra_installer#2]
Hi,
I tried your latest version on RG280V with OD beta FW. When starting any rom on your Atari 2600 (RA) emulator I always get an error "unsupported video mode > 160x250 RGB565". Other emulators seem to work fine. Also standalone Retroarch works with my 2600 roms. Any idea?

Other than that: great work! Your project was exactly what I was searching for to combine SimpleMenu and RA. 
Kind regards,
Marc

**Comment by eduardofilo** [comment]
> Hi,
> I tried your latest version on RG280V with OD beta FW. When starting any rom on your Atari 2600 (RA) emulator I always get an error "unsupported video mode > 160x250 RGB565". Other emulators seem to work fine. Also standalone Retroarch works with my 2600 roms. Any idea?
> 
> Other than that: great work! Your project was exactly what I was searching for to combine SimpleMenu and RA.
> Kind regards,
> Marc

Hi Marc.

I don't own the RG280V to test but the RG350M with a higher resolution and that's because it doesn't give me that problem. Try to deactivate the video filter that will surely is activate. Once you have the 2600 game opened press `Select + X`. Go to `Main menu` by pressing B and then follow the path `Settings > Video > Remove Video Filter`. If there was no filter activated as I expected, delete the following file through DinguxCmdr:

/usr/local/home/.retroarch/config/Stella 2014/Stella 2014.cfg

That way you will get the default configuration for Atari 2600, which I suppose will be more secure.

Good luck...
