### ISSUE TITLE
More wrapper requests

### ISSUE THREAD

**Issue by litaniast** [eduardofilo/RG350_ra_installer#4]
* GB, GBC for mGBA: mGBA can also run GB and GBC games. It runs slow for GBA in RG280V, but GB and GBC games run fine. If people want to run GB games with SGB border, it would be good choice.
* Sega CD for Picodrive: a few Sega CD games can't get full speed in Genesis Plus GX, but they run fine on Picodrive. (e.g. Night Striker)
* Famicom Disk System for FCEUmm: It uses .fds extension. Also it needs turn on RetroArch notifications because it uses system message of RetroArch for disk eject/side change

**Comment by eduardofilo** [comment]
I will consider it. Thanks...

**Comment by eduardofilo** [comment]
@litaniast I close this issue because I am going to archive this repository. The development of the installer will continue on the new repository https://github.com/eduardofilo/RG350_auto_ra_installer
The new repository is intended in a self service manner. With them, through parameterization, you will can generate any OPK wrapper you like.
Thanks by your comments.
